# Generated by Django 2.1.1 on 2018-09-15 18:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=10, verbose_name='カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='Tinps',
            fields=[
                ('tinps_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('tinps_body', models.CharField(max_length=1000, verbose_name='本文')),
                ('slashed_cnt', models.IntegerField(default=0, verbose_name='パイスラ回数')),
                ('wached_cnt', models.IntegerField(default=0, verbose_name='閲覧回数')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('category', models.ManyToManyField(to='post.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, verbose_name='ユーザ名')),
                ('mail', models.EmailField(max_length=128, verbose_name='メールアドレス')),
                ('pwd', models.CharField(max_length=256, verbose_name='パスワード')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
            ],
        ),
        migrations.AddField(
            model_name='tinps',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post.User'),
        ),
    ]
