# Generated by Django 2.1.1 on 2018-09-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinps',
            name='category',
            field=models.ManyToManyField(blank=True, to='post.Category'),
        ),
    ]
