# Generated by Django 2.1.1 on 2018-09-16 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinps',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
