# Generated by Django 2.1.1 on 2018-09-23 01:04

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, verbose_name='ユーザ名')),
                ('mail', models.EmailField(max_length=128, verbose_name='メールアドレス')),
                ('pwd', models.CharField(max_length=256, verbose_name='パスワード')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
            ],
        ),
    ]
